name: deploy-staging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    env: 
      CDK_DIR: "."
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.STG_AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: CDK Diff
        if: contains(github.event_name, 'pull_request')
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: cdk-diff-stg-v2
          env-vars-for-codebuild: |
            CDK_DIR,
        env:
          CDK_DIR: ${{ env.CDK_DIR }}

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: cdk-deploy-stg-v2
          env-vars-for-codebuild: |
            CDK_DIR,
        env:
          CDK_DIR: ${{ env.CDK_DIR }}
